export const ONE_SEC_MILLISECONDS = 1000;
export const ONE_MIN_SECONDS = 60;
export const ONE_MIN_MILLISECONDS = ONE_SEC_MILLISECONDS * ONE_MIN_SECONDS;
export const sendEventDurationMins = ONE_SEC_MILLISECONDS * 10;